# import time
# import calendar
# import datetime
# # start=time.time()
# # print(start)
# # name=input("Enter your name")
# # end=time.time() 
# # print(end)
# # print(end-start)   


# # print("start")
# # print("1")
# # time.sleep(2)
# # print("2")
# # time.sleep(2)
# # print("3")
# # time.sleep(2)
# # print("Go!")

# # import time
# # x=time.localtime()
# # print(x.tm_year)
# # print(x.tm_mon)
# # print(x.tm_mday)
# # print(x.tm_hour)
# # print(x.tm_min)
# # print(x.tm_sec)
# """Current Date: 12-09-2026
# Weekday Number: 5"""
# # import time
# # x=time.localtime()
# # print(x.tm_mday,"-",x.tm_mon,"-",x.tm_year)
# # print(x.tm_wday)
# # x=time.localtime()
# # x1=time.gmtime()
# # print(x.tm_hour,":",x.tm_mday)
# # print(x1.tm_hour,":",x1.tm_min)
# # x=time.localtime()
# # print(time.strftime("Toady is :%A",x))
# # print(time.strftime("Date :%d-%m-%Y",x))
# # print(time.strftime("Time :%I:%M %p"))
# # date=input("Enter date")
# # d=time.strptime(date,("%d-%m-%Y"))
# # print("year:",d.tm_year)
# # print("month",d.tm_mon)
# # print("Day :",d.tm_mday)
# # date=input("Enter date and time (DD-MM-YYYY HH:MM):")
# # dt=time.strptime(date,"%d-%m-%Y %H:%M")
# # print("Year:",dt.tm_year)
# # print("Month :",dt.tm_mon)
# # print("Day :",dt.tm_mday)
# # print("Hour:",dt.tm_hour)
# # print("Minute :",dt.tm_min)
# # start=time.localtime()
# # s=time.time()
# # name=input("Enter name:")
# # print("Employee:",name)
# # time.sleep(2)
# # print(time.strftime("Login Time:%I:%M:%S %p",start))
# # end=time.localtime()
# # e=time.time()
# # print(time.strftime("logoit time:%I:%M:%S %p",end))
# # diff=e-s
# # print("Time spent:",round(diff,2),"Seconds")
# # g=time.gmtime()
# # a=time.localtime()
# # print(time.strftime("Local time:%I:%M:%S %p",a))
# # print(time.strftime("Utc time:%I:%M:%S %p",g))

# # year=int(input("Enter year:"))
# # month=int(input("Enter month:"))
# # day=int(input("Enter day:"))
# # x=calendar.month(year,month)
# # print(x)
# # print(calendar.isleap(year))
# # print(calendar.weekday(year,month,day))
# # n=calendar.weekday(year,month,day)
# # print(calendar.day_name[n])
# # print(calendar.day_abbr[n])
# # print(calendar.month_name[month])
# # print(calendar.month_abbr[month])
# # x=calendar.monthrange(year,month)
# # print("Total days:",x[1])
# # print("week first days:",x[0])
# # x=calendar.monthcalendar(year,month)
# # print(x[0])
# # year=int(input("Enter year:"))
# # print(calendar.calendar(year))
# # a=datetime.date.today()
# # print(a)
# x=datetime.datetime.now()
# print("Year:",x.year)
# print("Month:",x.month)
# print("Day:",x.day)
# print("Hour :",x.hour)
# print("Minutes:",x.minute)
# print("seconds:",x.second)


import demo2
print(__name__)